name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Carlos-Antonio95
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "gerando snake.svg"
          add: "dist/github-contribution-grid-snake.svg"
