name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Etapa obrigatória: clona o repositório para o ambiente da Action
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Gera a animação SVG
      - name: Gera animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Carlos-Antonio95
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Faz commit e push do arquivo gerado
      - name: Faz commit do Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "gerando snake.svg"
          add: "dist/github-contribution-grid-snake.svg"
